"""Initial schema.

Written by hand rather than autogenerated, so you can run `alembic upgrade head`
on a fresh database without first needing a live connection to diff against.
If you change app/db/models.py later, use `alembic revision --autogenerate`.

Revision ID: 0001
Revises:
"""
import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "macro_indicators",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(32), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(16), nullable=False, server_default="percent"),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_macro_indicators_code", "macro_indicators", ["code"])
    op.create_index("ix_macro_indicators_observed_on", "macro_indicators", ["observed_on"])
    op.create_index("uq_macro_code_date", "macro_indicators", ["code", "observed_on"], unique=True)

    op.create_table(
        "price_bars",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("ticker", sa.String(16), nullable=False),
        sa.Column("traded_on", sa.Date(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("source", sa.String(64), nullable=False, server_default="mystocks"),
    )
    op.create_index("ix_price_bars_ticker", "price_bars", ["ticker"])
    op.create_index("ix_price_bars_traded_on", "price_bars", ["traded_on"])
    op.create_index("uq_price_ticker_date", "price_bars", ["ticker", "traded_on"], unique=True)

    op.create_table(
        "bank_reports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("ticker", sa.String(16), nullable=False),
        sa.Column("period", sa.String(16), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("npl_ratio", sa.Float(), nullable=True),
        sa.Column("profit_after_tax", sa.Float(), nullable=True),
        sa.Column("loan_book", sa.Float(), nullable=True),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("raw_extraction", sa.Text(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_bank_reports_ticker", "bank_reports", ["ticker"])
    op.create_index("uq_report_ticker_period", "bank_reports", ["ticker", "period"], unique=True)

    op.create_table(
        "sector_scores",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("scored_on", sa.Date(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("signal", sa.String(8), nullable=False),
        sa.Column("components", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_sector_scores_scored_on", "sector_scores", ["scored_on"], unique=True)

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("sector_score_id", sa.Integer(), sa.ForeignKey("sector_scores.id"), nullable=True),
        sa.Column("level", sa.String(16), nullable=False),
        sa.Column("signal", sa.String(8), nullable=False),
        sa.Column("headline", sa.String(200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("alerts")
    op.drop_table("sector_scores")
    op.drop_table("bank_reports")
    op.drop_table("price_bars")
    op.drop_table("macro_indicators")
